### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by dansomething** [dansomething/coc-java-debug#21]
- [ ] Add note regarding possible slow startup times. #20
- [ ] Illustrate roughly how it works. #3
- [ ] Link to a full working example
- [ ] Possibly update "adapters" config? #14 
- [ ] Add note regarding no multi-session support. #16
- [ ] Improve profiles documentation? #7
- [ ] Add note regarding hot code replacement. #9 #31

**Comment by Konfekt** [comment]
Hello, thank you for creating this plug-in the quest for a debugging experience as convenient as IntelliJ's. I did not fully get to what extent this depends on Coc (in view of newer alternatives like [lsp](https://github.com/yegappan/lsp))?

**Comment by dansomething** [comment]
> Hello, thank you for creating this plug-in the quest for a debugging experience as convenient as IntelliJ's. I did not fully get to what extent this depends on Coc (in view of newer alternatives like [lsp](https://github.com/yegappan/lsp))?

This plugin uses Coc for convenience when interacting with the Java language server and for creating a simple user interface. For example, it is used to [execute LSP commands](https://github.com/dansomething/coc-java-debug/blob/main/src/index.ts#L34). This could be done with any LSP integration for Vim/Nvim, but it's very easy with Coc.  There's also the [main method selection](https://github.com/dansomething/coc-java-debug/blob/main/src/debugserver.ts#L55) user interface. That could be implemented in other ways, but Coc also makes it so easy. This whole plugin is intended to be the simplest solution to glue the pieces together. See [Readme#Goals](https://github.com/dansomething/coc-java-debug/blob/main/README.md#goals)
